--BASE DE DATOS
CREATE DATABASE PRUEBA_DESARROLLO

--TABLAS reservadas
CREATE TABLE TR_ESTADOS_CONSULTA(
	ID tinyint NOT NULL,
	DESCRIPCION varchar(50) NOT NULL,
 CONSTRAINT PK_TR_ESTADOS_CONSULTA PRIMARY KEY (ID) 
)

INSERT INTO TR_ESTADOS_CONSULTA(ID, DESCRIPCION) VALUES(1,'Ocupada'),(2, 'En espera')

CREATE TABLE TR_TIPO_CONSULTA(
	ID tinyint NOT NULL,
	DESCRIPCION varchar(50) NOT NULL,
 CONSTRAINT PK_TR_TIPO_CONSULTA PRIMARY KEY (ID) 
)

INSERT INTO TR_TIPO_CONSULTA(ID, DESCRIPCION) VALUES(1,'Pediatría'),(2, 'Urgencia'),(3, 'CGI')

--TABLAS DE MOVIMIENTOS

CREATE TABLE TM_CONSULTA(
	ID 					INT AUTO_INCREMENT  NOT NULL,
	CANTIDAD_PACIENTES  INT NOT NULL,
	NOMBRE_ESPECIALISTA VARCHAR(500) NOT NULL,
	ID_TIPO_CONSULTA   TINYINT NOT NULL,
	ID_ESTADO TINYINT NOT NULL,
	CONSTRAINT PK_TM_CONSULTA PRIMARY KEY (ID),
	CONSTRAINT FK_TM_CONSULTA_1 FOREIGN KEY (ID_TIPO_CONSULTA) REFERENCES TR_TIPO_CONSULTA(ID),
	CONSTRAINT FK_TM_CONSULTA_2 FOREIGN KEY (ID_ESTADO) REFERENCES TR_ESTADOS_CONSULTA(ID)
)

CREATE TABLE TM_PACIENTE(
	ID 	INT AUTO_INCREMENT NOT NULL,
	NOMBRE VARCHAR(500) NOT NULL,
	EDAD INT NOT NULL,
	NUMERO_HISTORIA_CLINICA INT NOT NULL,
	CONSTRAINT PK_TM_PACIENTE PRIMARY KEY (ID)
)

CREATE TABLE TM_PACIENTE_ANCIANO(
	ID 	INT AUTO_INCREMENT NOT NULL,
	ID_PACIENTE INT NOT NULL,
	TIENE_DIETA BIT NOT NULL,
	CONSTRAINT PK_TM_PACIENTE_ANCIANO PRIMARY KEY (ID),
	CONSTRAINT FK_TM_PACIENTE_ANCIANO_1 FOREIGN KEY (ID_PACIENTE) REFERENCES TM_PACIENTE(ID)
)

CREATE TABLE TM_PACIENTE_JOVEN(
	ID 	INT AUTO_INCREMENT NOT NULL,
	ID_PACIENTE INT NOT NULL,
	FUMADOR BIT NOT NULL,
	CONSTRAINT PK_TM_PACIENTE_JOVEN PRIMARY KEY (ID),
	CONSTRAINT FK_TM_PACIENTE_JOVEN_1 FOREIGN KEY (ID_PACIENTE) REFERENCES TM_PACIENTE(ID)
)

CREATE TABLE TM_PACIENTE_NINIO(
	ID 	INT AUTO_INCREMENT NOT NULL,
	ID_PACIENTE INT NOT NULL,
	RELACION_PESOS_ESTATURA INT NOT NULL,
	CONSTRAINT PK_TM_PACIENTE_NINIO PRIMARY KEY (ID),
	CONSTRAINT FK_TM_PACIENTE_NINIO_1 FOREIGN KEY (ID_PACIENTE) REFERENCES TM_PACIENTE(ID)
)

--niños 1-15 joven 16-40 anciano 41>
/*
El hospital le asigna a cada paciente una prioridad para su atención, que se determina teniendo en
cuenta lo siguiente:

Para los niños:
    • (1-5 años)
        ◦ Peso-estatura + 3
    • (6-12 años)
        ◦ Peso-estatura + 2
    • (13-15 años)
        ◦ Peso-estatura + 1

Para los jóvenes:
    • Si es fumador: Años de fumador/4 + 2
    • En cualquier otro caso: 2
Para los ancianos:
    • Si tiene dieta y está entre 60 y 100 años: Edad/20 + 4
Sí no:
Edad/30 + 3
Además, se sabe que cada paciente tiene un riesgo que se determina por:
    • (Edad * prioridad) / 100.

Y en el caso de los ancianos:
    • (Edad * prioridad)/100 + 5.3
*/